// src/app/models/time-entry.model.ts

/**
 * Identity of the device/browser that pressed "play" for an entry. Stamped on
 * the entry at start time so a shared (gist-synced) running timer records WHO
 * started it. Used to enforce that only that device can pause/stop/resume it.
 * Optional: legacy entries and backups created before this feature won't have it.
 */
export interface EntryOrigin {
  /** Stable per-browser id (device-local; never travels in the gist payload). */
  deviceId: string;
  /** Human-friendly device label (autogenerated, e.g. "Equipo-A3F9"). */
  deviceName: string;
  /** Browser family derived from the user agent (e.g. "Chrome", "Edge"). */
  browser: string;
}

export interface TimeEntry {
  id: string;
  title: string | null;
  description: string | null;
  startTime: number; // timestamp
  endTime: number; // timestamp
  duration: number; // in milliseconds
  startedBy?: EntryOrigin; // device/browser that pressed play (optional for legacy data)
}

// Model per a l'entrada que s'està executant (endTime i duration són fixos o calculats)
export type RunningTimeEntry = Omit<TimeEntry, 'endTime' | 'duration'> & {
  endTime: null;
  duration: 0; 
};

// Type guard
export function isRunningEntry(entry: TimeEntry | RunningTimeEntry): entry is RunningTimeEntry {
  return entry.endTime === null;
}

export interface DailySummary {
  date: string; // Format 'YYYY-MM-DD'
  totalDurationMs: number;
}

export interface WeeklySummary {
  hoursWorked: number;
  horasExtra: number;      // Suma de excesos diarios > 8h
  targetHours: number;
  remainingHours: number;  // Horas pendientes solo desde hoy hasta fin de semana
  weekStart: string;       // ISO date (Monday)
  weekEnd: string;         // ISO date (Sunday)
}

export interface DayGroup {
  date: string;
  entries: TimeEntry[];
  totalDurationMs: number;
}

export interface GlobalBalance {
  balanceHours: number; // Balance total en horas (positivo = extra, negativo = falta)
}